import { z } from 'zod';
import type { LogLevel, Overrides, Serializer } from '../generator';
import {
  ArrayExpressionNode,
  ExtendsClauseNode,
  GenericExpressionNode,
  IdentifierNode,
  InferClauseNode,
  LiteralNode,
  LOG_LEVELS,
  Logger,
  MappedTypeNode,
  ObjectExpressionNode,
  RawExpressionNode,
  UnionExpressionNode,
} from '../generator';
import { DatabaseMetadata, IntrospectorDialect } from '../introspector';

export type Config = {
  camelCase?: boolean;
  customImports?: CustomImports;
  defaultSchemas?: string[];
  envFile?: string;
  excludePattern?: string | null;
  includePattern?: string | null;
  logger?: Logger;
  logLevel?: LogLevel;
  outFile?: string | null;
  overrides?: Overrides;
  print?: boolean;
  serializer?: Serializer;
  singularize?: boolean | Record<string, string>;
  skipAutogeneratedFileComment?: boolean;
  typeMapping?: Record<string, string>;
  typeOnlyImports?: boolean;
  url?: string;
  verify?: boolean;
};

export type CustomImports = Record<string, string>;

const expressionNodeSchema = z.union([
  z.instanceof(ArrayExpressionNode),
  z.instanceof(ExtendsClauseNode),
  z.instanceof(GenericExpressionNode),
  z.instanceof(IdentifierNode),
  z.instanceof(InferClauseNode),
  z.instanceof(LiteralNode),
  z.instanceof(MappedTypeNode),
  z.instanceof(ObjectExpressionNode),
  z.instanceof(RawExpressionNode),
  z.instanceof(UnionExpressionNode),
  z.string(),
]);

const overridesSchema = z
  .object({ columns: z.record(z.string(), expressionNodeSchema).optional() })
  .optional();

export const configSchema = z.object({
  camelCase: z.boolean().optional(),
  customImports: z.record(z.string(), z.string()).optional(),
  defaultSchemas: z.array(z.string()).optional(),
  envFile: z.string().optional(),
  excludePattern: z.string().nullable().optional(),
  includePattern: z.string().nullable().optional(),
  logger: z.instanceof(Logger).optional(),
  logLevel: z.enum(LOG_LEVELS).optional(),
  outFile: z.string().nullable().optional(),
  overrides: overridesSchema.optional(),
  print: z.boolean().optional(),
  serializer: z
    .object({
      serializeFile: z.function({
        input: z.tuple([
          z.instanceof(DatabaseMetadata),
          z.instanceof(IntrospectorDialect),
          z
            .object({
              camelCase: z.boolean().optional(),
              customImports: z.record(z.string(), z.string()).optional(),
              defaultSchemas: z.string().array().optional(),
              overrides: overridesSchema.optional(),
              typeMapping: z.record(z.string(), z.string()).optional(),
            })
            .optional(),
        ]),
        output: z.string(),
      }),
    })
    .optional(),
  singularize: z
    .union([z.boolean(), z.record(z.string(), z.string())])
    .optional(),
  skipAutogeneratedFileComment: z.boolean().optional(),
  typeMapping: z.record(z.string(), z.string()).optional(),
  typeOnlyImports: z.boolean().optional(),
  url: z.string().optional(),
  verify: z.boolean().optional(),
});
