/**
 * This file was generated by kysely-codegen-sqlite.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface EnumTest {
  id: Generated<number | null>;
  role: "admin" | "user" | "guest" | null;
  status: Generated<"active" | "inactive" | "pending">;
}

export interface FooBar {
  false: number;
  id: Generated<number>;
  overridden: "OVERRIDDEN";
  true: number;
  userStatus: string | null;
}

export interface DB {
  enumTest: EnumTest;
  fooBar: FooBar;
}
